name: ci_build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    - name: Run
      uses: docker/setup-buildx-action@v3
      run: cd main && ./build.sh all